# Change these first
owner: Aissi17 # Your GitHub organization or username, where this repository lives
repo: upptime-fentech # The name of this repository

sites:
  - name: Fentech Carrefour
    url: https://carrefour.prod.clairvoyant.fentech.ai
    icon : https://carrefour.prod.clairvoyant.fentech.ai/img/logo.svg

status-website: # Status website (optional)
  baseUrl: /upptime-fentech
  name: https://aissi17.github.io/upptime-fentech/
